name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install backend test deps
        run: |
          python -m pip install --upgrade pip
          # playwright for frontend tests
          pip install playwright
          python -m playwright install --with-deps chromium

      - name: Run backend tests
        run: |
          python -m unittest discover -s backend/tests -v

      - name: Run frontend tests
        run: |
          python -m unittest discover -s frontend/tests -v

  docker-build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Build backend image
        run: docker build -t adventai/backend:ci ./backend
      - name: Build frontend image
        run: docker build -t adventai/frontend:ci ./frontend